### ISSUE TITLE
Implementation different from the origin paper

### ISSUE THREAD

**Issue by Genie-Liu** [leandrolcampos/dcn-v2#1]
Based on the original paper, I think the cross-network part should be like:

```python
x_cross = cross_layer(x_in, x_cross)
```
https://github.com/leandrolcampos/dcn-v2/blob/2d0f072ac1f42b41248964df08153cf18d6091cc/model.py#L120-L140

**Comment by leandrolcampos** [comment]
Hi @Genie-Liu,

Thanks for reporting the issue! I think you're right, and I plan to address it by the end of the week.

All the best,
